### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by EarthToAbigail** [abdullahemad12/indromida#1]
As a user, 
I can visit the home page of the website and click a Sign Up button
So that:
I can log in and create a new account using my Facebook, Twitter or Google account.

Acceptance Criteria:

- [ ] Sign Up or Create Account button or link on the landing page
- [ ] OAuth using Facebook
- [ ] OAuth using Twitter
- [ ] OAuth using Google
- [ ] Profile page for the user to enter his/her details
- [ ] Saving user details in the database
